const D=window.POOL_DATA,$=s=>document.querySelector(s);const app=$('#app');
const META={
Lou:{recent:'2–1',move:0,first:29.7,top3:67.7},Andy:{recent:'2–1',move:0,first:28.3,top3:66.4},Brian:{recent:'2–1',move:-1,first:14.1,top3:46.8},Sandora:{recent:'3–0',move:1,first:14.9,top3:48.2},Jay:{recent:'2–1',move:-1,first:6.4,top3:28.5},Nate:{recent:'1–2',move:0,first:2.5,top3:14.6},Shaffer:{recent:'2–1',move:2,first:2.1,top3:13.1},Tommy:{recent:'0–3',move:-2,first:0.8,top3:6.1},Pete:{recent:'1–2',move:0,first:0.9,top3:6.5},Mullane:{recent:'1–2',move:0,first:0.2,top3:2.2}};

const BYES={5:['Panthers','Chiefs'],6:['Bengals','Lions','Dolphins','Vikings'],7:['Bills','Jaguars','Chargers','Commanders'],8:['Texans','Saints','Giants','49ers'],9:['Steelers','Titans'],10:['Bears','Broncos','Eagles','Bucs'],11:['Falcons','Browns','Packers','Rams','Patriots','Seahawks'],12:[],13:['Ravens','Colts','Raiders','Jets'],14:['Cardinals','Cowboys']};
const WEEK_STARTS={4:'2026-09-29',5:'2026-10-06',6:'2026-10-13',7:'2026-10-20',8:'2026-10-27',9:'2026-11-03',10:'2026-11-10',11:'2026-11-17',12:'2026-11-24',13:'2026-12-01',14:'2026-12-08',15:'2026-12-15',16:'2026-12-22',17:'2026-12-29',18:'2027-01-05'};
function activeWeek(){if(D.live?.nextWeek)return D.live.nextWeek;let now=new Date(),w=4;Object.entries(WEEK_STARTS).forEach(([n,d])=>{if(now>=new Date(d+'T00:00:00'))w=+n});return w}
function byeWeekFor(team){for(const [w,teams] of Object.entries(BYES))if(teams.includes(team))return +w;return null}
function byePanel(){let w=activeWeek(),teams=BYES[w]||[];let owners=[];teams.forEach(t=>{let p=D.players.find(p=>p.teams.some(x=>x.team===t));if(p)owners.push({team:t,player:p.name})});return `<section class="bye-panel"><div><div class="eyebrow">UPCOMING AVAILABILITY · WEEK ${w}</div><h2>${teams.length?`${teams.length} NFL team${teams.length===1?' is':'s are'} on bye`:'No teams on bye this week'}</h2><p>${teams.length?owners.map(x=>`<span class="bye-owner"><b>${x.team}</b> · ${x.player}</span>`).join(''):'Every pool team has a chance to add a win this week.'}</p></div><div class="bye-next">${w<14?`Next: Week ${w+1} · ${(BYES[w+1]||[]).length?(BYES[w+1]||[]).join(', '):'No byes'}`:'Bye season complete'}</div></section>`}


const UNDRAFTED=[{team:'Dolphins',w:0,l:3,t:0,recent:'0–1'},{team:'Cardinals',w:1,l:2,t:0,recent:'0–1'}];
const WEEK4={
'Eagles':{opp:'Rams',where:'vs',time:'Sun 1:00 PM'},'Broncos':{opp:'49ers',where:'at',time:'Sun 4:25 PM'},'Raiders':{opp:'Chiefs',where:'vs',time:'Sun 4:25 PM'},
'Chiefs':{opp:'Raiders',where:'at',time:'Sun 4:25 PM'},'Cowboys':{opp:'Texans',where:'at',time:'Sun 1:00 PM'},'Vikings':{opp:'Dolphins',where:'vs',time:'Sun 4:05 PM'},
'Bills':{opp:'Patriots',where:'vs',time:'Sun 1:00 PM'},'Packers':{opp:'Bucs',where:'at',time:'Sun 1:00 PM'},'Browns':{opp:'Steelers',where:'vs',time:'Thu 8:15 PM'},
'Lions':{opp:'Panthers',where:'at',time:'Sun 8:20 PM'},'Steelers':{opp:'Browns',where:'at',time:'Thu 8:15 PM'},'Giants':{opp:'Cardinals',where:'vs',time:'Sun 1:00 PM'},
'Ravens':{opp:'Titans',where:'vs',time:'Sun 1:00 PM'},'Jaguars':{opp:'Bengals',where:'at',time:'Sun 1:00 PM'},'Jets':{opp:'Bears',where:'at',time:'Sun 1:00 PM'},
'Patriots':{opp:'Bills',where:'at',time:'Sun 1:00 PM'},'Bengals':{opp:'Jaguars',where:'vs',time:'Sun 1:00 PM'},'Colts':{opp:'Commanders',where:'at',time:'Sun 9:30 AM · London'},
'49ers':{opp:'Broncos',where:'vs',time:'Sun 4:25 PM'},'Chargers':{opp:'Seahawks',where:'at',time:'Sun 4:25 PM'},'Commanders':{opp:'Colts',where:'vs',time:'Sun 9:30 AM · London'},
'Seahawks':{opp:'Chargers',where:'vs',time:'Sun 4:25 PM'},'Bucs':{opp:'Packers',where:'vs',time:'Sun 1:00 PM'},'Saints':{opp:'Falcons',where:'vs',time:'Mon 8:15 PM'},
'Rams':{opp:'Eagles',where:'at',time:'Sun 1:00 PM'},'Panthers':{opp:'Lions',where:'vs',time:'Sun 8:20 PM'},'Falcons':{opp:'Saints',where:'at',time:'Mon 8:15 PM'},
'Texans':{opp:'Cowboys',where:'vs',time:'Sun 1:00 PM'},'Bears':{opp:'Jets',where:'vs',time:'Sun 1:00 PM'},'Titans':{opp:'Ravens',where:'at',time:'Sun 1:00 PM'},
'Dolphins':{opp:'Vikings',where:'at',time:'Sun 4:05 PM'},'Cardinals':{opp:'Giants',where:'at',time:'Sun 1:00 PM'}
};
function liveMatchup(team){if(!D.live)return null;let names=D.live.names||{},code=Object.keys(names).find(k=>names[k]===team),g=D.live.upcoming?.find(x=>x.away===code||x.home===code);if(!g)return null;let away=g.away===code,opp=away?g.home:g.away;return{where:away?'at':'vs',opp:names[opp]||opp,time:`${g.gameday} · ${g.gametime||''}`}}
function matchupChip(team){let w=activeWeek(),bw=byeWeekFor(team);if(bw===w)return `<div class="matchup bye-match"><span>${team}</span><b>BYE · WEEK ${w}</b></div>`;let m=liveMatchup(team)||(w===4?WEEK4[team]:null);return `<div class="matchup" style="--team:${COLORS[team]||'#334155'}"><span>${team}</span><b>${m?`${m.where} ${m.opp}`:'Schedule unavailable'}</b><small>${m?m.time:''}</small></div>`}
function undraftedPanel(){let wins=UNDRAFTED.reduce((n,t)=>n+t.w,0),games=UNDRAFTED.reduce((n,t)=>n+t.w+t.l+t.t,0);let comparable=[...D.players].sort((a,b)=>b.wins-a.wins);let ahead=comparable.filter(p=>p.wins>wins).length+1;return `<section class="panel undrafted"><div class="undrafted-head"><div><div class="eyebrow">THE TEAMS NOBODY WANTED</div><h2>Undrafted Watch</h2><p class="sub">Miami + Arizona are still keeping receipts, even if nobody drafted them.</p></div><div class="ghost-rank"><span>Combined</span><strong>${wins}–${games-wins}</strong><small>${(wins/games*100).toFixed(1)}% win rate</small></div></div><div class="undrafted-grid">${UNDRAFTED.map(t=>`<div class="undrafted-team" style="--team:${COLORS[t.team]}"><div><b>${t.team}</b><span>${t.w}–${t.l}${t.t?'-'+t.t:''}</span></div><small>Week 3: ${t.recent} · ${WEEK4[t.team].where} ${WEEK4[t.team].opp}</small></div>`).join('')}</div><div class="undrafted-snark"><b>Unofficial ghost-entry check:</b> their two-team total of ${wins} wins would currently sit around ${ahead}${ahead===1?'st':ahead===2?'nd':ahead===3?'rd':'th'} by raw wins — with the enormous asterisk that everyone else has three teams. Last season's undrafted pair finished with ${D.seasons.find(s=>s.year===2025).players.find(p=>p.name==='Unpicked Teams').wins} wins.</div></section>`}
function ahead(){let w=activeWeek();let sorted=standings();app.innerHTML=`<section class="panel"><div class="week-ahead-head"><div><div class="eyebrow">NEXT UP</div><h2>Week ${w} Ahead</h2><p class="sub">Every contestant's three NFL matchups in one place. Bye teams will automatically flip to a BYE card when their week arrives.</p></div></div><div class="ahead-grid">${sorted.map(p=>`<article class="ahead-card"><div class="ahead-player"><b>${p.name}</b><span>${p.wins} wins · ${p.recent?`${p.recent.w}–${p.recent.l}`:META[p.name].recent} last week</span></div>${p.teams.map(t=>matchupChip(t.team)).join('')}</article>`).join('')}</div></section>${undraftedPanel()}`}

const COLORS={Eagles:'#004C54',Broncos:'#FB4F14',Raiders:'#A5ACAF',Chiefs:'#E31837',Cowboys:'#869397',Vikings:'#4F2683',Bills:'#00338D',Packers:'#203731',Browns:'#FF3C00',Lions:'#0076B6',Steelers:'#FFB612',Giants:'#0B2265',Ravens:'#241773',Jaguars:'#00A5B5',Jets:'#125740',Patriots:'#C60C30',Bengals:'#FB4F14',Colts:'#002C5F','49ers':'#AA0000',Chargers:'#0080C6',Commanders:'#5A1414',Seahawks:'#69BE28',Bucs:'#D50A0A',Saints:'#D3BC8D',Rams:'#003594',Panthers:'#0085CA',Falcons:'#A71930',Texans:'#03202F',Bears:'#C83803',Titans:'#4B92DB'};
function standings(){return [...D.players].sort((a,b)=>b.wins-a.wins||b.perfect-a.perfect)}function pct(p){return p.games?p.wins/p.games:0}function movement(n){let m=META[n].move;return m>0?`<span class="move up">▲ ${m}</span>`:m<0?`<span class="move down">▼ ${Math.abs(m)}</span>`:`<span class="move same">—</span>`}function teamChip(t){let c=COLORS[t.team]||'#334155',w=activeWeek(),bw=byeWeekFor(t.team),onBye=bw===w;return `<span class="team ${onBye?'on-bye':''}" style="--team:${c}"><i></i><span>${t.team}</span><b>${t.w}-${t.l}${t.t?'-'+t.t:''}</b>${onBye?`<em>BYE W${w}</em>`:''}</span>`}
function table(ps){return `<div class="tablewrap"><table><thead><tr><th>Place</th><th>Player</th><th>Teams</th><th>Wins</th><th>Win %</th><th>Last Week</th><th>1st Chance</th><th>Top 3 Chance</th><th>Perfect</th></tr></thead><tbody>${ps.map((p,i)=>`<tr><td class="rank"><span>${i+1}</span>${movement(p.name)}</td><td><b>${p.name}</b></td><td><div class="teams">${p.teams.map(teamChip).join('')}</div></td><td><b>${p.wins}</b></td><td class="pct">${(pct(p)*100).toFixed(1)}%</td><td><span class="weekrec ${META[p.name].recent==='3–0'?'perfectrec':META[p.name].recent==='0–3'?'badrec':''}">${META[p.name].recent}</span></td><td><b>${META[p.name].first.toFixed(1)}%</b></td><td><b>${META[p.name].top3.toFixed(1)}%</b></td><td>${p.perfect}</td></tr>`).join('')}</tbody></table></div>`}
function home(){let s=standings(),lead=s[0],total=D.players.reduce((n,p)=>n+p.games,0);let tids=[
`<b>Sandora chose violence.</b> A 3–0 Week 3 from Detroit, Pittsburgh and the Giants was the league's only clean sweep and moved him into third. Apparently drafting three 2–1 teams is less exciting than drafting a juggernaut, but annoyingly effective.`,
`<b>Shaffer is running an NFL portfolio with one blue-chip stock and one flaming bag.</b> San Francisco is 3–0; the Chargers are 0–3. Somehow he still climbed two spots this week after a 2–1 showing.`,
`<b>Tommy's Week 3 should be deleted from the group chat.</b> Seattle, Tampa Bay and New Orleans combined for an 0–3 week. The Bucs are now 0–3, giving Tommy a very efficient way to turn three draft picks into three total wins.`,
`<b>Lou's late Raiders pick is doing heavy lifting.</b> Las Vegas is 3–0 while his Eagles just got handled by Chicago. Lou still owns a share of first, but the undefeated team he drafted 30th is currently his best asset.`,
`<b>Andy has two undefeated anchors.</b> Kansas City and Minnesota are both 3–0, which is covering nicely for Dallas at 1–2. His projection is essentially neck-and-neck with Lou for the league's best chance at first.`,
`<b>Mullane has discovered an innovative strategy: draft two teams that refuse to win.</b> Houston and Tennessee are both 0–3. Chicago's 2–1 record is currently responsible for 100% of his pool wins.`];
app.innerHTML=`<section class="hero"><div class="copy"><div class="eyebrow">2026 LEAGUE HQ · THROUGH WEEK 3</div><h1>Three teams.<br>No excuses.</h1><p>Standings, projections, draft receipts and statistically supported trash talk.</p></div><div class="leader"><span>Current leader</span><strong>${lead.name}</strong><small>${lead.wins} wins · ${META[lead.name].first.toFixed(1)}% projected chance of 1st</small></div></section>${byePanel()}<section class="cards"><div class="card"><span>Players</span><strong>${D.players.length}</strong></div><div class="card"><span>Pool games tracked</span><strong>${total}</strong></div><div class="card"><span>Perfect weeks</span><strong>${D.perfectWeeks.length}</strong></div><div class="card"><span>Week 3 mover</span><strong>Shaffer ▲2</strong></div></section><section class="panel"><h2>2026 Standings</h2><p class="sub">NFL ties count as losses. Arrows compare current place with the standings after Week 2.</p>${table(s)}<div class="method"><b>Projection note:</b> 1st/Top-3 chances come from a 200,000-season simulation. Current team records are blended with a .500 preseason prior to avoid treating three games as destiny; remaining games are simulated independently. Pool wins and the “worst team” tiebreaker are modeled; playoff-team tiebreakers are not yet included.</div></section>${undraftedPanel()}<section class="panel"><h2>Things Your Friends May Not Want to Discuss</h2><div class="tidbits">${tids.map(x=>`<div class="tidbit">${x}</div>`).join('')}</div></section>`}
function draft(){app.innerHTML=`<section class="panel"><h2>2026 Draft Board</h2><p class="sub">All 30 selections, in draft order.</p><div class="draftgrid">${D.draft.map(x=>`<div class="pick" style="border-left-color:${COLORS[x.team]||'#72e1a5'}"><b>#${x.pick}</b> ${x.player}<br><strong>${x.team}</strong></div>`).join('')}</div></section>`}function history(){let career=[...D.history].sort((a,b)=>b.wins-a.wins);app.innerHTML=`<section class="panel"><h2>Career League History</h2><div class="tablewrap"><table><thead><tr><th>Player</th><th>Games</th><th>Wins</th><th>Win %</th></tr></thead><tbody>${career.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.games}</td><td>${x.wins}</td><td class="pct">${typeof x.pct==='number'?(x.pct*100).toFixed(1)+'%':x.pct}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h2>Season Archive</h2><div class="historycards">${D.seasons.map(s=>`<div class="season"><h3>${s.year}</h3>${s.players.sort((a,b)=>b.wins-a.wins).map((p,i)=>`<div>${i+1}. <b>${p.name}</b> — ${p.wins} wins</div>`).join('')}</div>`).join('')}</div></section>`}function perfect(){let by={};D.perfectWeeks.forEach(x=>(by[x.player]??=[]).push(x.week));app.innerHTML=`<section class="panel"><h2>3–0 Weeks</h2><p class="sub">Every perfect week logged in the workbook.</p><div class="historycards">${Object.entries(by).sort((a,b)=>b[1].length-a[1].length).map(([n,w])=>`<div class="season"><h3>${n}</h3><strong>${w.length} perfect week${w.length==1?'':'s'}</strong><p>Week${w.length==1?'':'s'} ${w.join(', ')}</p></div>`).join('')}</div></section>`}function rules(){app.innerHTML=`<section class="panel"><h2>League Rules & Points</h2><div class="rules">${D.rules.map((r,i)=>`<div class="rule"><b>${String(i+1).padStart(2,'0')}</b>${r}</div>`).join('')}</div></section>`}let pages={home,ahead,draft,history,perfect,rules};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');pages[b.dataset.page]();scrollTo(0,0)});home();
