const D=window.POOL_DATA,$=s=>document.querySelector(s);const app=$('#app');
const META={
Lou:{recent:'2–1',move:0,first:29.7,top3:67.7},Andy:{recent:'2–1',move:0,first:28.3,top3:66.4},Brian:{recent:'2–1',move:-1,first:14.1,top3:46.8},Sandora:{recent:'3–0',move:1,first:14.9,top3:48.2},Jay:{recent:'2–1',move:-1,first:6.4,top3:28.5},Nate:{recent:'1–2',move:0,first:2.5,top3:14.6},Shaffer:{recent:'2–1',move:2,first:2.1,top3:13.1},Tommy:{recent:'0–3',move:-2,first:0.8,top3:6.1},Pete:{recent:'1–2',move:0,first:0.9,top3:6.5},Mullane:{recent:'1–2',move:0,first:0.2,top3:2.2}};

const BYES={5:['Panthers','Chiefs'],6:['Bengals','Lions','Dolphins','Vikings'],7:['Bills','Jaguars','Chargers','Commanders'],8:['Texans','Saints','Giants','49ers'],9:['Steelers','Titans'],10:['Bears','Broncos','Eagles','Bucs'],11:['Falcons','Browns','Packers','Rams','Patriots','Seahawks'],12:[],13:['Ravens','Colts','Raiders','Jets'],14:['Cardinals','Cowboys']};
const WEEK_STARTS={4:'2026-09-29',5:'2026-10-06',6:'2026-10-13',7:'2026-10-20',8:'2026-10-27',9:'2026-11-03',10:'2026-11-10',11:'2026-11-17',12:'2026-11-24',13:'2026-12-01',14:'2026-12-08',15:'2026-12-15',16:'2026-12-22',17:'2026-12-29',18:'2027-01-05'};
function activeWeek(){if(D.live?.displayWeek)return D.live.displayWeek;if(D.live?.nextWeek)return D.live.nextWeek;let now=new Date(),w=4;Object.entries(WEEK_STARTS).forEach(([n,d])=>{if(now>=new Date(d+'T00:00:00'))w=+n});return w}
function byeWeekFor(team){for(const [w,teams] of Object.entries(BYES))if(teams.includes(team))return +w;return null}
function byePanel(){let w=activeWeek(),teams=BYES[w]||[];let owners=[];teams.forEach(t=>{let p=D.players.find(p=>p.teams.some(x=>x.team===t));if(p)owners.push({team:t,player:p.name})});return `<section class="bye-panel"><div><div class="eyebrow">UPCOMING AVAILABILITY · WEEK ${w}</div><h2>${teams.length?`${teams.length} NFL team${teams.length===1?' is':'s are'} on bye`:'No teams on bye this week'}</h2><p>${teams.length?owners.map(x=>`<span class="bye-owner"><b>${x.team}</b> · ${x.player}</span>`).join(''):'Every pool team has a chance to add a win this week.'}</p></div><div class="bye-next">${w<14?`Next: Week ${w+1} · ${(BYES[w+1]||[]).length?(BYES[w+1]||[]).join(', '):'No byes'}`:'Bye season complete'}</div></section>`}


const UNDRAFTED=()=>D.live?D.live.undrafted.map(t=>({team:D.live.names[t.code]||t.code,w:t.w,l:t.l,t:t.t,recent:''})):[{team:'Dolphins',w:0,l:3,t:0,recent:'0–1'},{team:'Cardinals',w:1,l:2,t:0,recent:'0–1'}];
const WEEK4={
'Eagles':{opp:'Rams',where:'vs',time:'Sun 1:00 PM'},'Broncos':{opp:'49ers',where:'at',time:'Sun 4:25 PM'},'Raiders':{opp:'Chiefs',where:'vs',time:'Sun 4:25 PM'},
'Chiefs':{opp:'Raiders',where:'at',time:'Sun 4:25 PM'},'Cowboys':{opp:'Texans',where:'at',time:'Sun 1:00 PM'},'Vikings':{opp:'Dolphins',where:'vs',time:'Sun 4:05 PM'},
'Bills':{opp:'Patriots',where:'vs',time:'Sun 1:00 PM'},'Packers':{opp:'Bucs',where:'at',time:'Sun 1:00 PM'},'Browns':{opp:'Steelers',where:'vs',time:'Thu 8:15 PM'},
'Lions':{opp:'Panthers',where:'at',time:'Sun 8:20 PM'},'Steelers':{opp:'Browns',where:'at',time:'Thu 8:15 PM'},'Giants':{opp:'Cardinals',where:'vs',time:'Sun 1:00 PM'},
'Ravens':{opp:'Titans',where:'vs',time:'Sun 1:00 PM'},'Jaguars':{opp:'Bengals',where:'at',time:'Sun 1:00 PM'},'Jets':{opp:'Bears',where:'at',time:'Sun 1:00 PM'},
'Patriots':{opp:'Bills',where:'at',time:'Sun 1:00 PM'},'Bengals':{opp:'Jaguars',where:'vs',time:'Sun 1:00 PM'},'Colts':{opp:'Commanders',where:'at',time:'Sun 9:30 AM · London'},
'49ers':{opp:'Broncos',where:'vs',time:'Sun 4:25 PM'},'Chargers':{opp:'Seahawks',where:'at',time:'Sun 4:25 PM'},'Commanders':{opp:'Colts',where:'vs',time:'Sun 9:30 AM · London'},
'Seahawks':{opp:'Chargers',where:'vs',time:'Sun 4:25 PM'},'Bucs':{opp:'Packers',where:'vs',time:'Sun 1:00 PM'},'Saints':{opp:'Falcons',where:'vs',time:'Mon 8:15 PM'},
'Rams':{opp:'Eagles',where:'at',time:'Sun 1:00 PM'},'Panthers':{opp:'Lions',where:'vs',time:'Sun 8:20 PM'},'Falcons':{opp:'Saints',where:'at',time:'Mon 8:15 PM'},
'Texans':{opp:'Cowboys',where:'vs',time:'Sun 1:00 PM'},'Bears':{opp:'Jets',where:'vs',time:'Sun 1:00 PM'},'Titans':{opp:'Ravens',where:'at',time:'Sun 1:00 PM'},
'Dolphins':{opp:'Vikings',where:'at',time:'Sun 4:05 PM'},'Cardinals':{opp:'Giants',where:'at',time:'Sun 1:00 PM'}
};
function liveMatchup(team){if(!D.live)return null;let names=D.live.names||{},code=Object.keys(names).find(k=>names[k]===team),g=D.live.upcoming?.find(x=>x.away===code||x.home===code);if(!g)return null;let away=g.away===code,opp=away?g.home:g.away;return{where:away?'at':'vs',opp:names[opp]||opp,time:`${g.gameday} · ${g.gametime||''}`}}
function matchupChip(team){let w=activeWeek(),bw=byeWeekFor(team);if(bw===w)return `<div class="matchup bye-match"><span>${team}</span><b>BYE · WEEK ${w}</b></div>`;let m=liveMatchup(team)||(w===4?WEEK4[team]:null);return `<div class="matchup" style="--team:${COLORS[team]||'#334155'}"><span>${team}</span><b>${m?`${m.where} ${m.opp}`:'Schedule unavailable'}</b><small>${m?m.time:''}</small></div>`}
function undraftedPanel(){let undrafted=UNDRAFTED(),wins=undrafted.reduce((n,t)=>n+t.w,0),games=undrafted.reduce((n,t)=>n+t.w+t.l+t.t,0);let comparable=[...D.players].sort((a,b)=>b.wins-a.wins);let ahead=comparable.filter(p=>p.wins>wins).length+1;return `<section class="panel undrafted"><div class="undrafted-head"><div><div class="eyebrow">THE TEAMS NOBODY WANTED</div><h2>Undrafted Watch</h2><p class="sub">Miami + Arizona are still keeping receipts, even if nobody drafted them.</p></div><div class="ghost-rank"><span>Combined</span><strong>${wins}–${games-wins}</strong><small>${(wins/games*100).toFixed(1)}% win rate</small></div></div><div class="undrafted-grid">${undrafted.map(t=>`<div class="undrafted-team" style="--team:${COLORS[t.team]}"><div><b>${t.team}</b><span>${t.w}–${t.l}${t.t?'-'+t.t:''}</span></div><small>${D.live?`Through Week ${D.live.throughWeek}`:`Week 3: ${t.recent}`} · ${(liveMatchup(t.team)||WEEK4[t.team]).where} ${(liveMatchup(t.team)||WEEK4[t.team]).opp}</small></div>`).join('')}</div><div class="undrafted-snark"><b>Unofficial ghost-entry check:</b> their two-team total of ${wins} wins would currently sit around ${ahead}${ahead===1?'st':ahead===2?'nd':ahead===3?'rd':'th'} by raw wins — with the enormous asterisk that everyone else has three teams. Last season's undrafted pair finished with ${D.seasons.find(s=>s.year===2025).players.find(p=>p.name==='Unpicked Teams').wins} wins.</div></section>`}
function remainingSOS(){
 if(!D.live?.remainingSchedule||!D.live?.teamRecords)return [];
 const rec=D.live.teamRecords,sched=D.live.remainingSchedule;
 const strength=code=>{let r=rec[code]||{w:0,l:0,t:0,g:0},g=r.g||r.w+r.l+r.t;return g?(r.w+.5*r.t)/g:.5};
 return D.players.map(p=>{let teams=p.teams.map(t=>{let games=sched[t.code]||[];return{team:t.team,games:games.length,sos:games.length?games.reduce((n,g)=>n+strength(g.opponent),0)/games.length:0}}),games=teams.reduce((n,t)=>n+t.games,0);return{name:p.name,sos:games?teams.reduce((n,t)=>n+t.sos*t.games,0)/games:0,teams}}).sort((a,b)=>b.sos-a.sos);
}
function sosTable(){
 let rows=remainingSOS();if(!rows.length)return "";
 let body=rows.map((r,i)=>"<tr><td>"+(i+1)+"</td><td><b>"+r.name+"</b></td><td><b>"+(r.sos*100).toFixed(1)+"%</b></td><td>"+r.teams.map(t=>t.team+" "+(t.sos*100).toFixed(1)+"%").join(" · ")+"</td></tr>").join("");
 return '<section class="panel"><div class="eyebrow">THE ROAD AHEAD</div><h2>Remaining Strength of Schedule</h2><p class="sub">Ordered from toughest remaining slate to lightest.</p><div class="tablewrap"><table><thead><tr><th>Rank</th><th>Player</th><th>Opponent %</th><th>By team</th></tr></thead><tbody>'+body+'</tbody></table></div><div class="method"><b>Method:</b> current opponent records across every remaining game; ties count as half. Higher values indicate a tougher schedule.</div></section>';
}
function ahead(){let w=activeWeek();let sorted=standings();app.innerHTML=`<section class="panel"><div class="week-ahead-head"><div><div class="eyebrow">NEXT UP</div><h2>Week ${w} Ahead</h2><p class="sub">Every contestant's three NFL matchups in one place. Bye teams will automatically flip to a BYE card when their week arrives.</p></div></div><div class="ahead-grid">${sorted.map(p=>`<article class="ahead-card"><div class="ahead-player"><b>${p.name}</b><span>${p.wins} wins · ${p.recent?`${p.recent.w}–${p.recent.l}`:META[p.name].recent} last week</span></div>${p.teams.map(t=>matchupChip(t.team)).join('')}</article>`).join('')}</div></section>${undraftedPanel()}`}

const COLORS={Eagles:'#004C54',Broncos:'#FB4F14',Raiders:'#A5ACAF',Chiefs:'#E31837',Cowboys:'#869397',Vikings:'#4F2683',Bills:'#00338D',Packers:'#203731',Browns:'#FF3C00',Lions:'#0076B6',Steelers:'#FFB612',Giants:'#0B2265',Ravens:'#241773',Jaguars:'#00A5B5',Jets:'#125740',Patriots:'#C60C30',Bengals:'#FB4F14',Colts:'#002C5F','49ers':'#AA0000',Chargers:'#0080C6',Commanders:'#5A1414',Seahawks:'#69BE28',Bucs:'#D50A0A',Saints:'#D3BC8D',Rams:'#003594',Panthers:'#0085CA',Falcons:'#A71930',Texans:'#03202F',Bears:'#C83803',Titans:'#4B92DB'};
function standings(){return [...D.players].sort((a,b)=>b.wins-a.wins)}function pct(p){return p.games?p.wins/p.games:0}
let PROJ_CACHE={key:"",data:{}};
function projections(){
 const key=D.players.map(p=>p.teams.map(t=>`${t.w}-${t.l}-${t.t}`).join("/")).join("|");if(PROJ_CACHE.key===key)return PROJ_CACHE.data;
 let seed=2166136261;for(const ch of key)seed=Math.imul(seed^ch.charCodeAt(0),16777619)>>>0;
 const rand=()=>{seed+=0x6D2B79F5;let t=seed;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296};
 const n=25000,first={},top3={};D.players.forEach(p=>{first[p.name]=0;top3[p.name]=0});
 for(let s=0;s<n;s++){
  let rows=D.players.map((p,i)=>{let tw=p.teams.map(t=>{let w=t.w,rem=Math.max(0,17-(t.w+t.l+t.t)),prob=(t.w+2)/(t.w+t.l+t.t+4);for(let k=0;k<rem;k++)if(rand()<prob)w++;return w});return{name:p.name,total:tw.reduce((a,b)=>a+b,0),worst:Math.min(...tw),seed:i}});
  rows.sort((a,b)=>b.total-a.total||b.worst-a.worst||a.seed-b.seed);first[rows[0].name]++;rows.slice(0,3).forEach(x=>top3[x.name]++);
 }
 let out={};D.players.forEach(p=>out[p.name]={first:first[p.name]*100/n,top3:top3[p.name]*100/n});PROJ_CACHE={key,data:out};return out;
}
function projection(n){return projections()[n]||{first:META[n]?.first||0,top3:META[n]?.top3||0}}
function cumulativeWins(p,w){return Object.entries(p.weekly||{}).filter(([wk])=>+wk<=w).reduce((n,[,r])=>n+(r.w||0),0)}
function rankMap(w){let base=D.players.map((p,i)=>({name:p.name,wins:cumulativeWins(p,w),seed:i})).sort((a,b)=>b.wins-a.wins||a.seed-b.seed),out={};base.forEach((p,i)=>out[p.name]=i+1);return out}
function movementValue(n){let w=D.live?.throughWeek||3;if(w<=1)return 0;if(D.live?.scoreboard?.week>w){let prev=rankMap(w),now={};standings().forEach((p,i)=>now[p.name]=i+1);return (prev[n]||now[n])-(now[n]||prev[n])}let now=rankMap(w),prev=rankMap(w-1);return (prev[n]||now[n])-(now[n]||prev[n])}
function movement(n){let m=D.live?movementValue(n):META[n].move;return m>0?`<span class="move up">▲ ${m}</span>`:m<0?`<span class="move down">▼ ${Math.abs(m)}</span>`:`<span class="move same">—</span>`}function teamChip(t){let c=COLORS[t.team]||'#334155',w=activeWeek(),bw=byeWeekFor(t.team),onBye=bw===w;return `<span class="team ${onBye?'on-bye':''}" style="--team:${c}"><i></i><span>${t.team}</span><b>${t.w}-${t.l}${t.t?'-'+t.t:''}</b>${onBye?`<em>BYE W${w}</em>`:''}</span>`}
function table(ps){return `<div class="tablewrap"><table><thead><tr><th>Place</th><th>Player</th><th>Teams</th><th>Wins</th><th>Win %</th><th>Last Week</th><th>1st Chance</th><th>Top 3 Chance</th><th>Perfect</th></tr></thead><tbody>${ps.map((p,i)=>`<tr><td class="rank"><span>${i+1}</span>${movement(p.name)}</td><td><b>${p.name}</b></td><td><div class="teams">${p.teams.map(teamChip).join('')}</div></td><td><b>${p.wins}</b></td><td class="pct">${(pct(p)*100).toFixed(1)}%</td><td><span class="weekrec ${(p.recent?.w===3)?'perfectrec':(p.recent?.l===3)?'badrec':''}">${p.recent?`${p.recent.w}–${p.recent.l}`:META[p.name].recent}</span></td><td><b>${projection(p.name).first.toFixed(1)}%</b></td><td><b>${projection(p.name).top3.toFixed(1)}%</b></td><td>${p.perfect}</td></tr>`).join('')}</tbody></table></div>`}
function weeklyTakeaways(){
 let w=D.live?.recapWeek||D.live?.throughWeek||3,ps=D.live?.recapPlayers||standings(),items=[],used=new Set();
 const add=(name,html)=>{if(!used.has(name)){items.push(html);used.add(name)}};
 const rec=p=>p.weekly?.[w]||{w:0,l:0};
 let perfect=ps.filter(p=>rec(p).w===3);
 perfect.forEach(p=>add(p.name,`<b>${p.name} chose violence.</b> A 3–0 Week ${w} means everybody else gets to hear about it until at least Thursday. Three teams entered; three wins left. Annoyingly efficient.`));
 let disaster=ps.filter(p=>rec(p).l===3);
 disaster.forEach(p=>add(p.name,`<b>${p.name} would like Week ${w} stricken from the record.</b> An 0–3 masterpiece: three teams, zero wins, and absolutely no reason to reopen the group chat until next week.`));
 let movers=ps.map(p=>({p,m:movementValue(p.name),r:rec(p)})).sort((a,b)=>b.m-a.m);
 if(movers[0]?.m>0)add(movers[0].p.name,`<b>${movers[0].p.name} has entered the chat.</b> A ${movers[0].r.w}–${movers[0].r.l} week moved him up ${movers[0].m} spot${movers[0].m===1?'':'s'}. Nothing like one good Sunday to suddenly develop very strong opinions about the standings.`);
 let fall=[...movers].sort((a,b)=>a.m-b.m)[0];
 if(fall?.m<0)add(fall.p.name,`<b>${fall.p.name} is headed in the wrong direction.</b> Week ${w} sent him down ${Math.abs(fall.m)} spot${Math.abs(fall.m)===1?'':'s'}. The standings are not technically judging him, but everyone else is allowed to.`);
 let carried=ps.map(p=>{let ts=[...p.teams].sort((a,b)=>b.w-a.w),share=p.wins?ts[0].w/p.wins:0;return{p,top:ts[0],share}}).sort((a,b)=>b.share-a.share)[0];
 if(carried&&carried.share>=.4)add(carried.p.name,`<b>${carried.p.name} is running a one-team operation.</b> The ${carried.top.team} have supplied ${carried.top.w} of his ${carried.p.wins} wins — ${Math.round(carried.share*100)}% of the entire portfolio. The other two picks are encouraged to begin participating whenever convenient.`);
 let ugly=ps.map(p=>({p,zeros:p.teams.filter(t=>t.w===0),best:[...p.teams].sort((a,b)=>b.w-a.w)[0]})).filter(x=>x.zeros.length).sort((a,b)=>b.zeros.length-a.zeros.length)[0];
 if(ugly)add(ugly.p.name,`<b>${ugly.p.name}'s draft board is developing a problem.</b> ${ugly.zeros.map(t=>t.team).join(' and ')} ${ugly.zeros.length===1?'is':'are'} still sitting on zero wins. ${ugly.best.team} is currently being asked to carry a workload that was not in the job description.`);
 let balanced=ps.map(p=>({p,spread:Math.max(...p.teams.map(t=>t.w))-Math.min(...p.teams.map(t=>t.w))})).sort((a,b)=>a.spread-b.spread||b.p.wins-a.p.wins)[0];
 if(balanced)add(balanced.p.name,`<b>${balanced.p.name} is refusing to provide easy material.</b> His three teams are separated by only ${balanced.spread} win${balanced.spread===1?'':'s'}. No obvious disaster, no ridiculous carry job — just irritating competence.`);
 let late=[...D.draft].sort((a,b)=>b.pick-a.pick).map(x=>{let p=ps.find(p=>p.name===x.player),t=p?.teams.find(t=>t.team===x.team);return{x,t,p}}).filter(z=>z.t).sort((a,b)=>b.t.w-a.t.w||b.x.pick-a.x.pick)[0];
 if(late)add(late.p.name,`<b>Late-round receipt alert:</b> ${late.x.player} grabbed the ${late.x.team} at pick #${late.x.pick}, and they already have ${late.t.w} win${late.t.w===1?'':'s'}. Somewhere, an earlier pick is quietly hoping nobody scrolls over to the Draft tab.`);
 let leader=[...ps].sort((a,b)=>b.wins-a.wins)[0];
 if(leader)add(leader.name,`<b>${leader.name} currently owns the big chair.</b> ${leader.wins} wins puts him on top through Week ${w}. Enjoy the view; this league has a long history of turning screenshots into evidence.`);
 return items.slice(0,6);
}
function home(){let s=standings(),lead=s[0],total=D.players.reduce((n,p)=>n+p.games,0);let tids=D.live?weeklyTakeaways():[
`<b>Sandora chose violence.</b> A 3–0 Week 3 from Detroit, Pittsburgh and the Giants was the league's only clean sweep and moved him into third. Apparently drafting three 2–1 teams is less exciting than drafting a juggernaut, but annoyingly effective.`,
`<b>Shaffer is running an NFL portfolio with one blue-chip stock and one flaming bag.</b> San Francisco is 3–0; the Chargers are 0–3. Somehow he still climbed two spots this week after a 2–1 showing.`,
`<b>Tommy's Week 3 should be deleted from the group chat.</b> Seattle, Tampa Bay and New Orleans combined for an 0–3 week. The Bucs are now 0–3, giving Tommy a very efficient way to turn three draft picks into three total wins.`,
`<b>Lou's late Raiders pick is doing heavy lifting.</b> Las Vegas is 3–0 while his Eagles just got handled by Chicago. Lou still owns a share of first, but the undefeated team he drafted 30th is currently his best asset.`,
`<b>Andy has two undefeated anchors.</b> Kansas City and Minnesota are both 3–0, which is covering nicely for Dallas at 1–2. His projection is essentially neck-and-neck with Lou for the league's best chance at first.`,
`<b>Mullane has discovered an innovative strategy: draft two teams that refuse to win.</b> Houston and Tennessee are both 0–3. Chicago's 2–1 record is currently responsible for 100% of his pool wins.`];
app.innerHTML=`<section class="hero"><div class="copy"><div class="eyebrow">2026 LEAGUE HQ · THROUGH WEEK ${D.live?.throughWeek||3}</div><h1>Three teams.<br>No excuses.</h1><p>Standings, projections, draft receipts and statistically supported trash talk.</p></div><div class="leader"><span>Current leader</span><strong>${lead.name}</strong><small>${lead.wins} wins · ${projection(lead.name).first.toFixed(1)}% projected chance of 1st</small></div></section>${byePanel()}<section class="cards"><div class="card"><span>Players</span><strong>${D.players.length}</strong></div><div class="card"><span>Pool games tracked</span><strong>${total}</strong></div><div class="card"><span>Perfect weeks</span><strong>${D.perfectWeeks.length}</strong></div><div class="card"><span>Latest completed week</span><strong>Week ${D.live?.throughWeek||3}</strong></div></section><section class="panel"><h2>2026 Standings</h2><p class="sub">NFL ties count as losses. Tied win totals remain tied during the season until the league's playoff-team and worst-team tiebreakers can be applied.</p>${table(s)}<div class="method"><b>Projection note:</b> 1st/Top-3 chances come from a deterministic 25,000-season simulation that recalculates when live standings change. Current team records are blended with a .500 preseason prior to avoid treating three games as destiny; remaining games are simulated independently. Pool wins and the “worst team” tiebreaker are modeled; playoff-team tiebreakers are not yet included.</div></section>${undraftedPanel()}<section class="panel"><h2>Things Your Friends May Not Want to Discuss</h2><div class="tidbits">${tids.map(x=>`<div class="tidbit">${x}</div>`).join('')}</div></section>`}
let TREND_FOCUS=null;
const TREND_COLORS=["#72e1a5","#ff6b78","#58a6ff","#f5c451","#b794f4","#ff9f43","#38d9a9","#f783ac","#74c0fc","#c0eb75"];
function trend(){
 const completed=D.live?.throughWeek||Math.max(1,...D.players.flatMap(p=>Object.keys(p.weekly||{}).map(Number))),liveWeek=D.live?.scoreboard?.week>completed?D.live.scoreboard.week:null,maxWeek=liveWeek||completed;
 const names=D.players.map(p=>p.name),series=names.map((name,i)=>{let p=D.players.find(x=>x.name===name),pts=[],total=0;for(let w=1;w<=maxWeek;w++){total+=p.weekly?.[w]?.w||0;if(liveWeek===w){let lp=D.players.find(x=>x.name===name);total=cumulativeWins(p,completed)+(lp?.recent?.w||0)}pts.push({w,v:total})}return{name,color:TREND_COLORS[i],pts}});
 const maxWins=Math.max(3,...series.flatMap(s=>s.pts.map(p=>p.v))),yMax=Math.ceil(maxWins/3)*3,W=1000,H=520,L=58,R=24,T=24,B=52,x=w=>L+(w-1)*((W-L-R)/Math.max(1,maxWeek-1)),y=v=>T+(yMax-v)*((H-T-B)/yMax);
 let grid="";for(let v=0;v<=yMax;v+=Math.max(1,Math.ceil(yMax/6)))grid+=`<line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}"/><text x="${L-12}" y="${y(v)+4}" text-anchor="end">${v}</text>`;for(let w=1;w<=maxWeek;w++)grid+=`<text x="${x(w)}" y="${H-20}" text-anchor="middle">${w}</text>`;
 let paths=series.map(s=>{let d=s.pts.map((p,j)=>`${j?'L':'M'} ${x(p.w)} ${y(p.v)}`).join(" "),focused=!TREND_FOCUS||TREND_FOCUS===s.name;return`<g class="trend-series ${focused?'':'muted'}" data-name="${s.name}"><path d="${d}" stroke="${s.color}"/>${s.pts.map(p=>`<circle cx="${x(p.w)}" cy="${y(p.v)}" r="${TREND_FOCUS===s.name?5:3}" fill="${s.color}"><title>${s.name} · Week ${p.w}: ${p.v} wins</title></circle>`).join("")}</g>`}).join("");
 app.innerHTML=`<section class="panel trend-panel"><div class="eyebrow">SEASON RACE</div><h2>Standings History</h2><p class="sub">Cumulative pool wins by week. Click a contestant in the legend to focus their line; click again to reset.</p><div class="trend-legend">${series.map(s=>`<button class="${TREND_FOCUS===s.name?'selected':''}" data-trend="${s.name}" style="--line:${s.color}"><i></i>${s.name}</button>`).join("")}</div><div class="trend-wrap"><svg class="trend-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Cumulative wins by week"><g class="trend-grid">${grid}</g><text class="axis-label" x="${(L+W-R)/2}" y="${H-2}" text-anchor="middle">Week</text><text class="axis-label" transform="translate(14 ${(T+H-B)/2}) rotate(-90)" text-anchor="middle">Total wins</text>${paths}</svg></div>${liveWeek?`<div class="method"><b>Live Week ${liveWeek}:</b> finalized games are included in the current endpoint of each line.</div>`:''}</section>`;
 document.querySelectorAll("[data-trend]").forEach(b=>b.onclick=()=>{TREND_FOCUS=TREND_FOCUS===b.dataset.trend?null:b.dataset.trend;trend()});
}
function draft(){app.innerHTML=`<section class="panel"><h2>2026 Draft Board</h2><p class="sub">All 30 selections, in draft order.</p><div class="draftgrid">${D.draft.map(x=>`<div class="pick" style="border-left-color:${COLORS[x.team]||'#72e1a5'}"><b>#${x.pick}</b> ${x.player}<br><strong>${x.team}</strong></div>`).join('')}</div></section>`}function history(){let career=[...D.history].sort((a,b)=>b.wins-a.wins);app.innerHTML=`<section class="panel"><h2>Career League History</h2><div class="tablewrap"><table><thead><tr><th>Player</th><th>Games</th><th>Wins</th><th>Win %</th></tr></thead><tbody>${career.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.games}</td><td>${x.wins}</td><td class="pct">${typeof x.pct==='number'?(x.pct*100).toFixed(1)+'%':x.pct}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h2>Season Archive</h2><div class="historycards">${D.seasons.map(s=>`<div class="season"><h3>${s.year}</h3>${s.players.sort((a,b)=>b.wins-a.wins).map((p,i)=>`<div>${i+1}. <b>${p.name}</b> — ${p.wins} wins</div>`).join('')}</div>`).join('')}</div></section>`}function perfect(){let by={};D.perfectWeeks.forEach(x=>(by[x.player]??=[]).push(x.week));app.innerHTML=`<section class="panel"><h2>3–0 Weeks</h2><p class="sub">Every perfect week logged in the workbook.</p><div class="historycards">${Object.entries(by).sort((a,b)=>b[1].length-a[1].length).map(([n,w])=>`<div class="season"><h3>${n}</h3><strong>${w.length} perfect week${w.length==1?'':'s'}</strong><p>Week${w.length==1?'':'s'} ${w.join(', ')}</p></div>`).join('')}</div></section>`}function rules(){app.innerHTML=`<section class="panel"><h2>League Rules & Points</h2><div class="rules">${D.rules.map((r,i)=>`<div class="rule"><b>${String(i+1).padStart(2,'0')}</b>${r}</div>`).join('')}</div></section>`}let pages={home,ahead,trend,draft,history,perfect,rules};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');pages[b.dataset.page]();scrollTo(0,0)});home();

window.addEventListener("pool-live-update",()=>{let b=document.querySelector("nav button.active"),fn=b&&pages[b.dataset.page];if(fn)fn()});
